### ISSUE TITLE
App crashes with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ipereziriarte** [amplitude/Amplitude-Android#88] opened 2016-03-23 17:08 UTC
Hi,
I've updated amplitude to version 2.5.1 and I'm getting a lot of crashes. Here's the stacktrace:

> Fatal Exception: java.lang.IndexOutOfBoundsException
       at java.util.LinkedList.remove(LinkedList.java:660)
       at com.amplitude.api.AmplitudeClient.mergeEventsAndIdentifys(AmplitudeClient.java:844)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:816)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:789)
       at com.amplitude.api.AmplitudeClient$7.run(AmplitudeClient.java:783)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Can you help me please?

**Comment by djih** [comment] 2016-03-23 18:58
Hi @ipereziriarte sorry for the crashes. Are you able to reproduce the crash yourself? Any other details you can share? We are working on a patch now

**Comment by djih** [comment] 2016-03-23 20:20
@ipereziriarte does your app run on multiple processes?

**Comment by ipereziriarte** [comment] 2016-03-23 20:30
Yes. It the app runs in 2 processes

**Comment by djih** [comment] 2016-03-23 20:57
Ok I think I know what the problem is. We use Android Sharedpreferences to store some meta data (like event id, identify id), and it's known to not be process-safe (http://stackoverflow.com/questions/4693387/sharedpreferences-and-thread-safety).

During updateServer, we fetch the last eventId and last identifyId, and use them to fetch events to upload. I can imagine a scenario where the last eventId or last identifyId value fetched is out of date, but the total event count is correct. The number of events the SDK can merge is less than the number it's expecting to merge, and thus triggers the out of bounds. The solution is to migrate the meta data out of SharedPrefs into the db.

**Comment by djih** [comment] 2016-03-25 02:51
@ipereziriarte the fix is merged, we will release a new version either tomorrow or early next week

**Closed** 2016-03-25 02:51 UTC

**Comment by aminelaadhari** [comment] 2016-03-29 18:22
We had the issue but with a single process

**Comment by djih** [comment] 2016-03-29 18:31
@aminelaadhari  good to know! The patch should fix it for single processes as well.

**Comment by djih** [comment] 2016-03-29 19:51
Fix is pushed in [v2.6.0](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.6.0), note it will take 1-2 hours for the new version to appear in Maven.
