### ISSUE TITLE
NoSuchMethodException: getAdvertisingIdInfo Google Play Services 6.1.11

### ISSUE THREAD

**Issue by osipovas** [amplitude/Amplitude-Android#14] opened 2014-10-23 20:11 UTC
Using Google Play Services Version 6.1.11 we encounter the following error. Amplitude Version 1.4.1

Stack Trace:

com.amplitude.api.DeviceInfo﹕ Encountered an error connecting to Google Play Services
    java.lang.NoSuchMethodException: getAdvertisingIdInfo [class android.content.Context]
            at java.lang.Class.getConstructorOrMethod(Class.java:472)
            at java.lang.Class.getMethod(Class.java:857)
            at com.amplitude.api.DeviceInfo.l(DeviceInfo.java:181)
            at com.amplitude.api.Amplitude$1.run(Amplitude.java:121)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oleg404** [comment] 2015-02-24 15:21
I have same problem , When you can update?

**Comment by osipovas** [comment] 2015-02-24 15:33
This exception stopped being thrown in version 1.4.2 or 1.4.3. Maybe @curtisliu can confirm.

**Comment by oleg404** [comment] 2015-02-24 15:58
I have version 1.4.3

**Comment by curtisliu** [comment] 2015-02-24 22:54
Is this actually causing a crash? What version of the Android SDK are you building against? We should be catching this exception, so it shouldn't cause any crashes.

**Comment by ui-philip** [comment] 2015-03-10 15:28
No, it isn't causing a crash. When looking in the Android log it looks like a crash, but that is caused by the Google Play Services, which is later caught and handled by the Amplitude SDK.

It seems some devices just don't support the advertising ID. I just tested on a Samsung Note 3 and it is not able to get the advertising ID (GooglePlayServicesRepairableException: Google Play Services not available). Weird...

**Comment by allanca** [comment] 2015-03-19 00:47
Sounds like this is working as expected. Closing for now.

**Closed by allanca** 2015-03-19 00:47 UTC
