### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by aminelaadhari** [amplitude/Amplitude-Android#90] opened 2016-03-29 15:23 UTC
We started getting this crash since amplitude 2.5.1 and segment integration 1.0.1

Fatal Exception: java.lang.IndexOutOfBoundsException
       at java.util.LinkedList.remove(LinkedList.java:660)
       at com.amplitude.api.AmplitudeClient.mergeEventsAndIdentifys(AmplitudeClient.java:844)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:816)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:789)
       at com.amplitude.api.AmplitudeClient$7.run(AmplitudeClient.java:783)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by djih** [comment] 2016-03-29 18:17
Duplicate of https://github.com/amplitude/Amplitude-Android/issues/88. Pushing fix today, thanks for reporting

**Closed by djih** 2016-03-29 18:17 UTC
