### ISSUE TITLE
User session has lots of 0 seconds 

### ISSUE THREAD

**Issue by RockyLin** [amplitude/Amplitude-Android#134] opened 2017-03-08 01:38 UTC
![screen shot 2017-03-08 at 9 37 37 am](https://cloud.githubusercontent.com/assets/6820710/23686167/ed5711f8-03e2-11e7-99d1-dbf2b1b7b50b.png)

**Comment by djih** [comment] 2017-03-09 21:10
@RockyLin what kind of app do you have? Do users open and close the app without doing anything? Do you send push notifications? Those things can cause a lot of 0 second sessions

**Comment by RockyLin** [comment] 2017-03-10 14:52
@djih 
It's a video app. It's weird that so many 0 secs session. There is no way users open and close app in a blink without doing anything, it doesn't make any sense!
At first, I thought it was App crashes. But it doesn't match the crashlytics result. 
In the app,  we send push notifications generated by user's activity.

Thanks for your reply!

**Comment by djih** [comment] 2017-03-10 19:54
@RockyLin my guess is if the user receives a notification but doesn't open the app, the SDK might log that as a 0 second session. You could try setting `Amplitude.getInstance().trackSessionEvents(false);` and seeing if that reduces the 0 second sessions

**Comment by RockyLin** [comment] 2017-03-11 09:24
@djih 
Thanks! Where should I put this Amplitude.getInstance().trackSessionEvents(false)? In MyApplication?
I already set Amplitude.getInstance().initialize(this, "Key").enableForegroundTracking(this) in it.

**Comment by djih** [comment] 2017-03-13 18:14
@RockyLin  you can chain it on after the enable foreground tracking, like this:

`Amplitude.getInstance().initialize(this, "key").enableForegroundTracking(this).trackSessionEvents(false);`

**Comment by hamen** [comment] 2017-05-12 10:07
Hi, I'm seeing a similar issue as well.
I'm wondering what happens if I disable `trackSessionEvents`: do I lose all the **Start session/End session** data or Amplitude will just filter out the sessions that don't contain any event?

As a reference, here is what I see on my dashboard:

<img width="340" alt="screen shot 2017-05-12 at 11 33 46 am" src="https://cloud.githubusercontent.com/assets/19003/25992491/f60fdfda-3706-11e7-9765-2d035a1df5c4.png"><img width="305" alt="screen shot 2017-05-12 at 11 33 33 am" src="https://cloud.githubusercontent.com/assets/19003/25992492/f62867e4-3706-11e7-956e-9e489dea6401.png">

Thank you for the help.

**Comment by RockyLin** [comment] 2017-05-14 05:26
@djih

**Comment by djih** [comment] 2017-05-15 18:47
@hamen @RockyLin if you disable `trackSessionEvents`, the SDK will stop sending start and end session events completely. The SDK will send start and end session events via activity life cycle callbacks when the app comes into the foreground and when it goes into the background. From your screenshots it looks like the user opens your app very briefly and then closes it (either due to pop up notifications or something), which triggers the callbacks to send the session events, generating a lot of 0 second sessions. 

I recommend setting `trackSessionEvents` to false, and removing the call to `enable to see if that reduces the 0 second sessions.

**Comment by curiousily** [comment] 2017-06-08 15:00
@djih,

Is it possible to introduce a method that can set the minimum duration for a session to be considered/tracked?

**Comment by RockyLin** [comment] 2017-06-14 09:54
@djih 
I disabled trackSessionEvents like you said, however, it doesn't work...

**Comment by djih** [comment] 2017-07-21 22:17
Another thing I forgot to mention is that you can adjust the `minTimeBetweenSessionsMillis`. Basically how long the app has to be in the background / inactive for the next interaction / event to start a new session. By default it's 5 minutes, but you can increase it.

For example, imagine your user opens the app, picks a song to play, and then minimizes the app. After the song finishes, they reopen the app, pick the next song, etc. If the song lasts for more than 5 minutes (aka more than 5 minutes pass between the opening of the app), then that would trigger a new session. So now you have 2 sessions each with only 2 events Open App + Play Song, and they could be very fast (<1 second). That might cause the high number of 0 second sessions. What you could do is increase the `minTimeBetweenSessionsMillis` to say something like 10 or 15 minutes (so 
600,000 to 900,000 milliseconds), that way when the user opens the app the second time, it's still considered the same session, and now you have 1 single session spanning across all the events.

It really depends on each of your app's specific use case, but it's something you could try.

**Comment by dan-tee** [comment] 2017-11-03 11:29
We are also hugely struggling with this issue. We have many sessions shorter than 10 milliseconds on Android, not on iOS.

@RockyLin: One problem we already found out about is setting user properties while the app is in background. This would create these kind of 0 second sessions. On our request a flag outOfSession has been added to the identify method that sets a user property. This should prevent a session from being created when you update a user property.

@djih: Can push notifications also lead to sessions if all triggered events and changed user properties are marked as out of session?

**Comment by josedlpozo** [comment] 2017-11-03 15:09
Hi!
We have had the same issue. Amplitude were tracking sessions shorter than a second even that we know the user didn't open the app. We were investigating this bug in our code and also in Amplitude SDK code.

Then we have realized that we instantiate the Amplitude instance in our Application onCreate method. This method is called when user receives a push notification, or also if you register a BroadcastReceiver in AndroidManifest file(we have registered a BroadcastReceiver for connectivity changes). So, these sessions with less than seconds of duration were caused by these issues and not because a user opening the app.

As a workaround, we have registered an ActivityLifeCycleCallbacks in our Application onCreate method, and initialize Amplitude in onActivityCreated callback method. Once we have initialized Amplitude, we can unregister this ActivityLifeCycleCallbacks.
```java
public class MyApplication extends Application {
    
    @Override public void onCreate() {
        super.onCreate();
        this.registerActivityLifecycleCallbacks(lifecycleCallbacks);
    }
    
    private final ActivityLifecycleCallbacks lifecycleCallbacks = new ActivityLifecycleCallbacks() {
        @Override public void onActivityCreated(final Activity activity, final Bundle bundle) {
            Amplitude.getInstance().initialize(this, API_KEY);
            unregisterActivityLifecycleCallbacks(this);
        }

        @Override public void onActivityStarted(final Activity activity) {}

        @Override public void onActivityResumed(final Activity activity) {}

        @Override public void onActivityPaused(final Activity activity) {}

        @Override public void onActivityStopped(final Activity activity) {}

        @Override public void onActivitySaveInstanceState(final Activity activity, final Bundle bundle) {}

        @Override public void onActivityDestroyed(final Activity activity) {}
    };
}
```

This way we can avoid to initialize Amplitude if the user has not opened the app :)

**Closed** 2019-11-21 01:10 UTC
